WIDTH, HEIGHT = 600, 700

PADDLE_WIDTH, PADDLE_HEIGHT = 100, 15
PADDLE_Y = HEIGHT - 40
PADDLE_SPEED = 8.0

BALL_RADIUS = 8

BRICK_ROWS = 7
BRICK_COLUMNS = 10
N_BRICKS = BRICK_ROWS * BRICK_COLUMNS
BRICK_WIDTH = WIDTH // BRICK_COLUMNS
BRICK_HEIGHT = 20
BRICK_TOP = 100

BALL_SPEED_X = 5.0
BALL_SPEED_Y = -5.0
